### ISSUE TITLE
Error when upgrading pulumi/pulumi to 3.162.0

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-go-provider#332]
### What happened?

When I combined the latest pulumi/pulumi, I got the following error:
```
 could not import github.com/pulumi/pulumi-go-provider (-: # github.com/pulumi/pulumi-go-provider
     /home/rshade/github/Go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.25.0/provider.go:754:57: undefined: rpc.ResourceProvider_StreamInvokeServer) (typecheck)
        provider "github.com/pulumi/pulumi-go-provider"```

### Example

None required

### Output of `pulumi about`

```
Dependencies:
NAME            VERSION
@pulumi/pulumi  3.162.0
@types/node     22.13.1
ts-node         10.9.2
typescript      4.9.5
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
